FROM debian:bookworm-slim

RUN apt-get update \
 && apt-get dist-upgrade -y \
            curl ca-certificates apt-transport-https debian-archive-keyring gnupg

RUN adduser --no-create-home  --disabled-login tyk

RUN rm -fv /usr/bin/passwd /usr/bin/adduser || true

RUN apt-get purge -y gnupg \
 && apt-get autoremove -y \
 && rm -rf /root/.cache

COPY tyk-sync /opt/tyk-sync/tyk-sync
WORKDIR /opt/tyk-sync
USER tyk

ENTRYPOINT ["./tyk-sync"]

CMD ["--help"]
