name: Run tests

on:
  pull_request:
  push:
    branches:
     - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    outputs:
      latest-tag: $(steps.get-latest-tag.outputs.tag)
    steps:
      - name: Checkout Tyk Sync
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.x

      - uses: actions-ecosystem/action-get-latest-tag@v1.6.0
        id: get-latest-tag
        with:
          semver_only: true

      - name: Run unit tests
        run: go test ./...

  sbom:
    uses: TykTechnologies/github-actions/.github/workflows/sbom.yaml@main
    if: ${{ github.event_name  == 'pull_request' ||  github.event_name == 'push' }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      DEPDASH_URL: ${{ secrets.DEPDASH_URL }}
      DEPDASH_KEY: ${{ secrets.DEPDASH_KEY }}
      ORG_GH_TOKEN: ${{ secrets.ORG_GH_TOKEN }}
      DOCKER_IMAGE: "tykio/tyk-sync:${{ needs.run-tests.outputs.latest-tag }})"
